# ==================================================
# SERVER
# ==================================================
server:
  port: 9102
#  servlet:
#    context-path: /eureka

# ==================================================
# SPRING
# ==================================================
spring:
#  application:
#    name: saigneur-discovery
  cloud:
    config:
      import-check:
        enabled: false

# ==================================================
# EUREKA
# ==================================================
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://78.138.45.243:9102/eureka/

# ==================================================
# MANAGEMENT
# ==================================================
management:
  endpoints:
    web:
      exposure:
        include: refresh

