# ==================================================
# SERVER
# ==================================================
server:
  port: 9004
  error:
    include-message: always

# ==================================================
# SPRING
# ==================================================
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    config:
      import-check:
        enabled: false

# ==================================================
# EUREKA
# ==================================================
eureka:
  instance:
    hostname: 78.138.45.243
#    port: 9102
  client:
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      defaultZone: http://78.138.45.243:9102/eureka/

# ==================================================
# MANAGEMENT
# ==================================================
management:
  endpoints:
    web:
      exposure:
        include: refresh



#spring:
#  cloud:
#    loadbalancer:
#      cache:
#        caffeine:
#          spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
#spring:
#  cache:
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s