# ==================================================
# SERVER
# ==================================================
server:
  port: 9004

# ==================================================
# SPRING
# ==================================================
spring:
  cloud:
    config:
      import-check:
        enabled: false

# ==================================================
# EUREKA
# ==================================================
eureka:
  instance:
    hostname: 78.138.45.243
#    port: 9102
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:9102/eureka/

# ==================================================
# MANAGEMENT
# ==================================================
management:
  endpoints:
    web:
      exposure:
        include: refresh

