# ==================================================
# SERVER
# ==================================================
server:
  port: 9102

# ==================================================
# SPRING
# ==================================================
spring:
  cloud:
    config:
      import-check:
        enabled: false

# ==================================================
# EUREKA
# ==================================================
eureka:
#  instance:
#    hostname: 78.138.45.243
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# ==================================================
# MANAGEMENT
# ==================================================
management:
  endpoints:
    web:
      exposure:
        include: refresh

