# ==================================================
# SERVER
# ==================================================
server:
  port: 9001
  error:
    include-message: always

# ==================================================
# SPRING
# ==================================================
spring:
  application:
    name: saigneur-gateway-web
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: saigneur-utilisateur
          uri: lb://saigneur-utilisateur
          predicates:
            - Path=/msaigneur-utilisateur/**
          filters:
            - RewritePath=/msaigneur-utilisateur/(?<path>.*), /$\{path}
        - id: saigneur-candidat
          uri: lb://saigneur-candidat
          predicates:
            - Path=/msaigneur-candidat/**
          filters:
            - RewritePath=/msaigneur-candidat/(?<path>.*), /$\{path}
        - id: saigneur-utilitaire
          uri: lb://saigneur-utilitaire
          predicates:
            - Path=/msaigneur-utilitaire/**
          filters:
            - RewritePath=/msaigneur-utilitaire/(?<path>.*), /$\{path}


#          filters:
#            - StripPrefix=1

#        - id: saigneur-utilisateur
#          uri: lb://saigneur-utilisateur
#          predicates:
#            - Path=/saigneur-utilisateur/**
#          filters:
#            - RewritePath=/saigneur-utilisateur/(?<path>.*), /$\{path}

#          uri: http://78.138.45.243:9002

#      - id: saigneur-candidat
#        uri: http://78.138.45.243:9003
#        predicates:
#        - Path=/msaigneur-candidat/**
#        filters:
#        - RewritePath=/msaigneur-candidat/(?<path>.*), /$\{path}
#      - id: saigneur-utilitaire
#        uri: http://78.138.45.243:9004
#        predicates:
#        - Path=/msaigneur-utilitaire/**
#        filters:
#        - RewritePath=/msaigneur-utilitaire/(?<path>.*), /$\{path}

# ==================================================
# EUREKA
# ==================================================
eureka:
  client:
    service-url:
      defaultZone: http://78.138.45.243:9102/eureka/

# ==================================================
# MANAGEMENT
# ==================================================
#management:
#  endpoint:
#    gateway:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
##        include: gateway
#        include: "*"
##        include: refresh



#spring:
#  cloud:
#    loadbalancer:
#      cache:
#        caffeine:
#          spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
#spring:
#  cache:
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
