# ==================================================
# SERVER
# ==================================================
server:
  port: 9001
  error:
    include-message: always

# ==================================================
# SPRING
# ==================================================
spring:
  application:
    name: saigneur-gateway-web
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: saigneur-utilisateur
          uri: lb://saigneur-utilisateur
          predicates:
            - Path=/msaigneur-utilisateur/**
          filters:
            - RewritePath=/msaigneur-utilisateur/(?<path>.*), /$\{path}
        - id: saigneur-candidat
          uri: lb://saigneur-candidat
          predicates:
            - Path=/msaigneur-candidat/**
          filters:
            - RewritePath=/msaigneur-candidat/(?<path>.*), /$\{path}
        - id: saigneur-utilitaire
          uri: lb://saigneur-utilitaire
          predicates:
            - Path=/msaigneur-utilitaire/**
          filters:
            - RewritePath=/msaigneur-utilitaire/(?<path>.*), /$\{path}

# ==================================================
# EUREKA
# ==================================================
eureka:
  client:
    service-url:
      defaultZone: http://78.138.45.243:9102/eureka/

## ==================================================
## LOGGING
## ==================================================
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG

# ==================================================
# MANAGEMENT
# ==================================================
management:
  endpoints:
    web:
      exposure:
        include: "*"

#management:
#  endpoint:
#    gateway:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
##        include: gateway
#        include: "*"
##        include: refresh



#spring:
#  cloud:
#    loadbalancer:
#      cache:
#        caffeine:
#          spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
#spring:
#  cache:
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
