# ==================================================
# SERVER
# ==================================================
server:
  port: 9001
  error:
    include-message: always

# ==================================================
# SPRING
# ==================================================
spring:
  application:
    name: saigneur-gateway-web
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      routes:
        - id: saigneur-utilisateur
#          uri: http://78.138.45.243:9002
          uri: lb://saigneur-utilisateur
          predicates:
            - Path=/msaigneur-candidat/**
        - id: saigneur-candidat
#            uri: http://78.138.45.243:9003
            uri: lb://saigneur-candidat
            predicates:
              - Path=/msaigneur-candidat/**
        - id: saigneur-utilitaire
#            uri: http://78.138.45.243:9004
            uri: lb://saigneur-utilitaire
            predicates:
              - Path=/msaigneur-utilitaire/**
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false

# ==================================================
# EUREKA
# ==================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://78.138.45.243:9102/eureka/

# ==================================================
# MANAGEMENT
# ==================================================
management:
  endpoints:
    web:
      exposure:
        include: refresh



#spring:
#  cloud:
#    loadbalancer:
#      cache:
#        caffeine:
#          spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
#spring:
#  cache:
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
