# ==================================================
# SERVER
# ==================================================
server:
  port: 9003
  error:
    include-message: always

# ==================================================
# SPRING
# ==================================================
spring:
  application:
    name: saigneur-candidat
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
  cloud:
    config:
      import-check:
        enabled: false

# ==================================================
# EUREKA
# ==================================================
eureka:
  client:
    # To register to the eureka server
    register-with-eureka: true
    # To fetch the registry from the eureka server
    fetchRegistry: true
    service-url:
      defaultZone: http://78.138.45.243:9102/eureka/

  instance:
    # The instance hostname
    hostname: 78.138.45.243:9102
    # The instance unique id
    instanceId: ${eureka.instance.hostname}:${spring.application.name}
    # A bench of health information end-points provided by eureka
    statusPageUrl: http://${eureka.hostname}/
    healthCheckUrl: http://${eureka.hostname}/actuator/health
    secureHealthCheckUrl: http://${eureka.hostname}/actuator/health

# ==================================================
# MANAGEMENT
# ==================================================
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh



#spring:
#  cloud:
#    loadbalancer:
#      cache:
#        caffeine:
#          spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
#spring:
#  cache:
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
