# ==================================================
# SERVER
# ==================================================
server:
  port: 9003
  error:
    include-message: always

# ==================================================
# SPRING
# ==================================================
spring:
  application:
    name: saigneur-candidat
  cloud:
    config:
      import-check:
        enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false

# ==================================================
# EUREKA
# ==================================================
eureka:
#  instance:
#    hostname: 78.138.45.243
#    port: 9102
#    preferIpAddress: true
#    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://78.138.45.243:9102/eureka/

# ==================================================
# MANAGEMENT
# ==================================================
management:
  endpoints:
    web:
      exposure:
        include: refresh



#spring:
#  cloud:
#    loadbalancer:
#      cache:
#        caffeine:
#          spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
#spring:
#  cache:
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
