# ==================================================
# SERVER
# ==================================================
server:
  port: 9102
#  servlet:
#    context-path: /eureka

# ==================================================
# SPRING
# ==================================================
spring:
  application:
    name: saigneur-discovery
  cloud:
    config:
      import-check:
        enabled: false

# ==================================================
# EUREKA
# ==================================================
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://31.207.33.14:9102/eureka/

# ==================================================
# MANAGEMENT
# ==================================================
management:
  endpoints:
    web:
      exposure:
        include: "*"

