# ==================================================
# SERVER
# ==================================================
server:
  port: 9102
  servlet:
    context-path: /eureka

# ==================================================
# SPRING
# ==================================================
spring:
  cloud:
    config:
      import-check:
        enabled: false

# ==================================================
# EUREKA
# ==================================================
eureka:
  instance:
    hostname: 78.138.45.243
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# ==================================================
# MANAGEMENT
# ==================================================
management:
  endpoints:
    web:
      exposure:
        include: refresh

